# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 21:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_from', models.CharField(max_length=200)),
                ('tickets_to', models.CharField(max_length=200)),
                ('tickets_date', models.DateTimeField(default=datetime.datetime(2016, 12, 21, 21, 33, 30, 907809))),
                ('tickets_class', models.CharField(max_length=200)),
                ('tickets_places', models.IntegerField()),
                ('tickets_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
