# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tickets_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 21, 34, 14, 302782)),
        ),
    ]
