# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20161221_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tickets_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 23, 39, 53, 637478)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tickets_date',
            field=models.DateField(),
        ),
    ]
