# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 19:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20161221_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tickets_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 19, 36, 2, 557359)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tickets_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
