# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20161224_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tickets_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 19, 37, 28, 656634)),
        ),
    ]
