# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20161224_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tickets_datetime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tickets_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
