# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20161225_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tickets_class',
            field=models.IntegerField(),
        ),
    ]
