# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20161225_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tickets_paid',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
